version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - docker build -t 361115084383.dkr.ecr.us-east-1.amazonaws.com/lichi:speedtest .
      
  build:
    commands:
      - docker push 361115084383.dkr.ecr.us-east-1.amazonaws.com/lichi:speedtest
      - echo Image pushed to ECR: 361115084383.dkr.ecr.us-east-1.amazonaws.com/lichi:speedtest

artifacts:
  files: 
    - '**/*'

